### ISSUE TITLE
Dynamic list issue - Error[500]

### ISSUE THREAD

**Issue by ajatula** [parcelvoy/platform#299] opened 2023-10-16 18:56 UTC
Hi,

**Can someone please help me with the following issues?**
When trying to make a dynamic list I get to see the following error:
<img width="445" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/990718f6-c325-41b7-b280-ef52f530e567">

After refreshing the dynamic list is added - however, when I try to open it I get to see Error [500]:
<img width="1154" alt="Scherm­afbeelding 2023-10-16 om 20 52 16" src="https://github.com/parcelvoy/platform/assets/6264407/8f4152b3-9f71-4e71-88d8-84fc9e88b4d0">

I've setup parcelvoy using docker compose (https://docs.parcelvoy.com/overview/quick-start)

**Comment by pushchris** [comment] 2023-10-16 22:09
Hello @ajatula! That particular issue should've been resolve by #291. Could you try please pulling the latest and see if you are still experiencing the issue? You will most likely need to archive any previously created lists.

**Comment by ajatula** [comment] 2023-10-17 08:37
@pushchris thx! I pulled the latest version :) 

I'm getting a new error when trying to make a new project (please see the screenshot below:) , any ideas?

<img width="1603" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/ddc0625c-4e8e-4795-9440-d111fb77bf8a">
 
Below my docker api logs:
2023-10-17 10:32:58 [1697531578041] ERROR (8 on e64936c7da5c): error
2023-10-17 10:32:58     ctx: {
2023-10-17 10:32:58       "request": {
2023-10-17 10:32:58         "method": "GET",
2023-10-17 10:32:58         "url": "/api/admin/projects/all",
2023-10-17 10:32:58         "header": {
2023-10-17 10:32:58           "host": "api:3001",
2023-10-17 10:32:58           "connection": "close",
2023-10-17 10:32:58           "sec-ch-ua": "\"Google Chrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\"",
2023-10-17 10:32:58           "accept": "application/json, text/plain, */*",
2023-10-17 10:32:58           "sec-ch-ua-mobile": "?0",
2023-10-17 10:32:58           "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
2023-10-17 10:32:58           "sec-ch-ua-platform": "\"macOS\"",
2023-10-17 10:32:58           "sec-fetch-site": "same-origin",
2023-10-17 10:32:58           "sec-fetch-mode": "cors",
2023-10-17 10:32:58           "sec-fetch-dest": "empty",
2023-10-17 10:32:58           "referer": "http://localhost:3000/",
2023-10-17 10:32:58           "accept-encoding": "gzip, deflate, br",
2023-10-17 10:32:58           "accept-language": "nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,it;q=0.5",
2023-10-17 10:32:58           "cookie": "oauth={\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwib3JnYW5pemF0aW9uX2lkIjpudWxsLCJleHAiOjE2OTc1NjgyMTYsImlhdCI6MTY5NzQ4MTgxNn0.uZ-qMoeRjkIHHsWTuvxUQsNQfxdCijw-IjX5Uq3mqlM\",\"expires_at\":\"2023-10-17T18:43:36.117Z\"}; oauth.sig=dp4f-9lvAOqmQySfG-rEjb4Mkss; ph_[YOUR_VALUE]_posthog=%7B%22distinct_id%22%3A%22018b3a3b-b6e1-7dab-a18a-5ea9bac8922c%22%2C%22%24device_id%22%3A%22018b3a3b-b6e1-7dab-a18a-5ea9bac8922c%22%2C%22%24user_state%22%3A%22anonymous%22%2C%22%24sesid%22%3A%5B1697490285437%2C%22018b3a3b-b6e4-71b6-aa88-6eb32c0c2ad9%22%2C1697489073892%5D%7D"
2023-10-17 10:32:58         }
2023-10-17 10:32:58       },
2023-10-17 10:32:58       "response": {
2023-10-17 10:32:58         "status": 404,
2023-10-17 10:32:58         "message": "Not Found",
2023-10-17 10:32:58         "header": {
2023-10-17 10:32:58           "vary": "Origin"
2023-10-17 10:32:58         }
2023-10-17 10:32:58       },
2023-10-17 10:32:58       "app": {
2023-10-17 10:32:58         "subdomainOffset": 2,
2023-10-17 10:32:58         "proxy": true,
2023-10-17 10:32:58         "env": "production"
2023-10-17 10:32:58       },
2023-10-17 10:32:58       "originalUrl": "/api/admin/projects/all",
2023-10-17 10:32:58       "req": "<original node req>",
2023-10-17 10:32:58       "res": "<original node res>",
2023-10-17 10:32:58       "socket": "<original node socket>"
2023-10-17 10:32:58     }
2023-10-17 10:32:58     error: {
2023-10-17 10:32:58       "originalStack": "TypeError: Cannot read properties of undefined (reading 'organization_id')\n    at Builder.<anonymous> (/usr/src/app/build/projects/ProjectService.js:53:95)\n    at compileCallback (/usr/src/app/node_modules/knex/lib/formatter/formatterUtils.js:7:12)\n    at rawOrFn (/usr/src/app/node_modules/knex/lib/formatter/wrappingFormatter.js:225:7)\n    at QueryCompiler_MySQL.whereWrapped (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:1095:17)\n    at QueryCompiler_MySQL.where (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:584:34)\n    at /usr/src/app/node_modules/knex/lib/query/querycompiler.js:135:40\n    at Array.forEach (<anonymous>)\n    at QueryCompiler_MySQL.select (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:134:16)\n    at QueryCompiler_MySQL.toSQL (/usr/src/app/node_modules/knex/lib/query/querycompiler.js:75:29)\n    at Builder.toSQL (/usr/src/app/node_modules/knex/lib/query/querybuilder.js:84:44)\n    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)\n    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:318:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)\n    at async Project.all (/usr/src/app/build/core/Model.js:93:25)\n    at async allProjects (/usr/src/app/build/projects/ProjectService.js:53:12)"
2023-10-17 10:32:58     }
2023-10-17 10:33:04 [1697531584619] ERROR (8 on e64936c7da5c): error
2023-10-17 10:33:04     ctx: {
2023-10-17 10:33:04       "request": {
2023-10-17 10:33:04         "method": "POST",
2023-10-17 10:33:04         "url": "/api/admin/projects",
2023-10-17 10:33:04         "header": {
2023-10-17 10:33:04           "host": "api:3001",
2023-10-17 10:33:04           "connection": "close",
2023-10-17 10:33:04           "content-length": "103",
2023-10-17 10:33:04           "sec-ch-ua": "\"Google Chrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\"",
2023-10-17 10:33:04           "accept": "application/json, text/plain, */*",
2023-10-17 10:33:04           "content-type": "application/json",
2023-10-17 10:33:04           "sec-ch-ua-mobile": "?0",
2023-10-17 10:33:04           "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
2023-10-17 10:33:04           "sec-ch-ua-platform": "\"macOS\"",
2023-10-17 10:33:04           "origin": "http://localhost:3000",
2023-10-17 10:33:04           "sec-fetch-site": "same-origin",
2023-10-17 10:33:04           "sec-fetch-mode": "cors",
2023-10-17 10:33:04           "sec-fetch-dest": "empty",
2023-10-17 10:33:04           "referer": "http://localhost:3000/",
2023-10-17 10:33:04           "accept-encoding": "gzip, deflate, br",
2023-10-17 10:33:04           "accept-language": "nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,it;q=0.5",
2023-10-17 10:33:04           "cookie": "oauth={\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwib3JnYW5pemF0aW9uX2lkIjpudWxsLCJleHAiOjE2OTc1NjgyMTYsImlhdCI6MTY5NzQ4MTgxNn0.uZ-qMoeRjkIHHsWTuvxUQsNQfxdCijw-IjX5Uq3mqlM\",\"expires_at\":\"2023-10-17T18:43:36.117Z\"}; oauth.sig=dp4f-9lvAOqmQySfG-rEjb4Mkss; ph_[YOUR_VALUE]_posthog=%7B%22distinct_id%22%3A%22018b3a3b-b6e1-7dab-a18a-5ea9bac8922c%22%2C%22%24device_id%22%3A%22018b3a3b-b6e1-7dab-a18a-5ea9bac8922c%22%2C%22%24user_state%22%3A%22anonymous%22%2C%22%24sesid%22%3A%5B1697490285437%2C%22018b3a3b-b6e4-71b6-aa88-6eb32c0c2ad9%22%2C1697489073892%5D%7D"
2023-10-17 10:33:04         }
2023-10-17 10:33:04       },
2023-10-17 10:33:04       "response": {
2023-10-17 10:33:04         "status": 404,
2023-10-17 10:33:04         "message": "Not Found",
2023-10-17 10:33:04         "header": {
2023-10-17 10:33:04           "vary": "Origin",
2023-10-17 10:33:04           "access-control-allow-origin": "http://localhost:3000"
2023-10-17 10:33:04         }
2023-10-17 10:33:04       },
2023-10-17 10:33:04       "app": {
2023-10-17 10:33:04         "subdomainOffset": 2,
2023-10-17 10:33:04         "proxy": true,
2023-10-17 10:33:04         "env": "production"
2023-10-17 10:33:04       },
2023-10-17 10:33:04       "originalUrl": "/api/admin/projects",
2023-10-17 10:33:04       "req": "<original node req>",
2023-10-17 10:33:04       "res": "<original node res>",
2023-10-17 10:33:04       "socket": "<original node socket>"
2023-10-17 10:33:04     }
2023-10-17 10:33:04     error: {
2023-10-17 10:33:04       "headers": {
2023-10-17 10:33:04         "Access-Control-Allow-Origin": "http://localhost:3000",
2023-10-17 10:33:04         "vary": "Origin"
2023-10-17 10:33:04       }
2023-10-17 10:33:04     }
2023-10-17 10:32:58 
2023-10-17 10:32:58   TypeError: Cannot read properties of undefined (reading 'organization_id')
2023-10-17 10:32:58       at createQueryBuilder (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:320:26)
2023-10-17 10:32:58       at knex (/usr/src/app/node_modules/knex/lib/knex-builder/make-knex.js:101:12)
2023-10-17 10:32:58       at Project.table (/usr/src/app/build/core/Model.js:225:16)
2023-10-17 10:32:58       at Project.build (/usr/src/app/build/core/Model.js:229:36)
2023-10-17 10:32:58       at Project.all (/usr/src/app/build/core/Model.js:93:36)
2023-10-17 10:32:58       at allProjects (/usr/src/app/build/projects/ProjectService.js:53:36)
2023-10-17 10:32:58       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-17 10:32:58       at async /usr/src/app/build/projects/ProjectController.js:47:16
2023-10-17 10:32:58       at async serve (/usr/src/app/node_modules/koa-static/index.js:59:5)
2023-10-17 10:32:58       at async cors (/usr/src/app/node_modules/@koa/cors/index.js:61:32)
2023-10-17 10:32:58       at async /usr/src/app/build/api.js:48:17
2023-10-17 10:32:58 
2023-10-17 10:33:04 
2023-10-17 10:33:04   TypeError: Cannot read properties of undefined (reading 'organization_id')
2023-10-17 10:33:04       at createProject (/usr/src/app/build/projects/ProjectService.js:73:32)
2023-10-17 10:33:04       at /usr/src/app/build/projects/ProjectController.js:75:57
2023-10-17 10:33:04       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-17 10:33:04       at async serve (/usr/src/app/node_modules/koa-static/index.js:59:5)
2023-10-17 10:33:04       at async cors (/usr/src/app/node_modules/@koa/cors/index.js:110:16)
2023-10-17 10:33:04       at async /usr/src/app/build/api.js:48:17
2023-10-17 10:33:04

**Comment by ajatula** [comment] 2023-10-17 12:32
@pushchris Can you please let me know if the following steps are correct to install parcelvoy locally?

1. pull the latest code 
2. perform the command 'mv .env.example .env' in:
- the root directory
-  apps/platform, and
- apps/ui
3. npm install from the root directory
4. npm start

**Comment by pushchris** [comment] 2023-10-17 13:37
That is very odd indeed! I am unable to replicate unfortunately, going to have to do some digging. Those are the correct steps for pulling from source. Do you have access to the database you are running this on? Can you check if anything is being inserted into the `rules` table when you create the list? And if so, is there a reference to that rule in the `rule_id` table in lists? Can you also check what the relationships are on the lists table?

**Comment by pushchris** [comment] 2023-10-17 13:47
Ok, one more thing to try:

If you run:
```
`SHOW CREATE TABLE `lists`;
```

Does it contain a foreign key to `rule_id` that contains a `ON DELETE` clause?

If so, run the following and let me know if it resolves the issue:
```
ALTER TABLE `lists` DROP FOREIGN KEY `lists_rule_id_foreign`;
```

If not we'll keep looking!

**Comment by ajatula** [comment] 2023-10-17 21:52
So after following the mentioned installation steps and running 'npm start' I get to see a database error and a 504-error in the browser:

**Database error:**
`[1697579181034] ERROR (20319 on MacBook-Pro-van-Anton.local): database error
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:3306",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:3306
              at Function.get (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/knex-builder/make-knex.js:44:26)
              at getSchemaBuilder (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/table-creator.js:71:17)
              at ensureTable (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/table-creator.js:10:10)
              at listCompleted (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:9)
              at Object.listAllAndCompleted (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:25:5)
              at Migrator.latest (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/Migrator.js:63:57)
              at migrate (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/config/database.ts:51:33)
              at exports.default (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/config/database.ts:82:15)
              at Function.init (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/app.ts:33:44)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
      "errno": -61,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 3306,
      "fatal": true,
      "originalStack": "Error: connect ECONNREFUSED 127.0.0.1:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1284:16)"
    }
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Function.get (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/knex-builder/make-knex.js:44:26)
    at getSchemaBuilder (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/table-creator.js:71:17)
    at ensureTable (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/table-creator.js:10:10)
    at listCompleted (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:9)
    at Object.listAllAndCompleted (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:25:5)
    at Migrator.latest (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/node_modules/knex/lib/migrations/migrate/Migrator.js:63:57)
    at migrate (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/config/database.ts:51:33)
    at exports.default (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/config/database.ts:82:15)
    at Function.init (/Users/antonjatula/Desktop/parcelvoy/platform-1.0.0-beta.4/apps/platform/src/app.ts:33:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true,
  originalStack: 'Error: connect ECONNREFUSED 127.0.0.1:3306\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1284:16)'
}`

**Browser error and another terminal error:**
<img width="1792" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/a5742d56-516c-4cf2-9bc7-f7b0fd19e7c4">

`Error occurred while proxying request localhost:3000/api/admin/profile to http://localhost:3001/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)`

**Comment by ajatula** [comment] 2023-10-17 22:04
If instead of 'npm start' I run 'docker compose up' I can get into my project and subsequently reproduce the errors with the dynamic list.

I tried to inspect the mysql database by doing the following steps in the terminal:

 `docker exec -it platform-100-beta4-mysql-1 bash`

`mysql -u root -p`

<img width="226" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/b9e7afc0-70dc-4f23-b042-c8d6fcca4619">

`use parcelvoy;`

<img width="224" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/ee51b78a-7974-46bc-a341-ec403c696f5e">

<img width="1007" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/85590f37-ac13-4a4d-ae63-9da6a6e570e1">

<img width="776" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/3c0bba87-5770-4eb0-8585-3d97bfb7fe57">

**Comment by ajatula** [comment] 2023-10-17 22:23
Can you check if anything is being inserted into the rules table when you create the list? 

yes :) 
<img width="1494" alt="Scherm­afbeelding 2023-10-18 om 00 09 21" src="https://github.com/parcelvoy/platform/assets/6264407/5a4775b7-0c60-4643-a402-cfda644cb7df">


And if so, is there a reference to that rule in the rule_id table in lists? 

<img width="1463" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/2f626b9b-53f0-4365-9d4c-f04e63dc06b7">

Can you also check what the relationships are on the lists table?
<img width="1167" alt="image" src="https://github.com/parcelvoy/platform/assets/6264407/67c1e4b9-ea20-430b-ad64-06c80df07f68">

**Comment by pushchris** [comment] 2023-10-18 13:00
The data you posted is definitely emblematic of the issue that was resolved by https://github.com/parcelvoy/platform/pull/291 in [v1.0.0-beta.4](https://github.com/parcelvoy/platform/releases/tag/v1.0.0-beta.4). The issue pertained to the list not properly associating the rule to itself so the list view would never load. I've been trying to reproduce what you are experiencing and have yet to get it to trigger in the latest docker version. Can we try two more things:
- If you are pulling the docker image from `latest` change to `1.0.0-beta.4` just to quadruple check its the right version
- Change whatever database value you are using to be different. This will autocreate a fresh database just to see if the issue is still potentially related to the database (though from your images it looks fine). It wont affect your previous database.

Thanks!

**Comment by ajatula** [comment] 2023-10-18 21:15
Changing the docker image from **latest** to **1.0.0-beta.4** solved it!! Thank you so much. I really appreciate it.

**Closed** 2023-10-19 13:24 UTC
